### ISSUE TITLE
Gulp dist failing

### ISSUE THREAD

**Issue by arch1t3ct** [lucascosta/facebook-js-ads-sdk#7]
Trying to build on Mac, here's what I get:

`
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Error loading /Users/architect/facebook-ads-sdk/dist/bundle.es6: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/Users/architect/facebook-ads-sdk/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at transform$1 (/Users/architect/facebook-ads-sdk/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /Users/architect/facebook-ads-sdk/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:7426:28
    at tryCatch (/Users/architect/facebook-ads-sdk/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:395:12)
    at invokeCallback (/Users/architect/facebook-ads-sdk/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:407:13)
    at /Users/architect/facebook-ads-sdk/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:168:7
    at flush (/Users/architect/facebook-ads-sdk/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:120:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
`

Both Bower and Gulp are globally installed. Dependancies are also installed. No code modification has been done. `gulp test` passes, but bundle fails with the same error as above. Version is 2.7.0.

P.S. Build is required to add AdsPixel.

**Comment by arch1t3ct** [comment]
I've also tried this on Debian 8.5. Same issue. Finally it hit me: both bower and npm are installing higher versions of modules than defined in bower.json and package.json files. This is due to the caret in front of the version number. Which is why builds are not working. Some of those packages introduced breaking changes in the code. Which ones - I don't know (babel rollup plugin most likely). I just removed all the caret and `gulp dist` started to work. So all you have to do on all dependancies is (example):

`rollup-plugin-babel": "^2.6.1"` change to `"rollup-plugin-babel": "2.6.1"`

**Comment by lucascosta** [comment]
Thanks for the tip @arch1t3ct. Next time we bump them I'll remote the carets.

**Comment by lucascosta** [comment]
Fixed
