### ISSUE TITLE
Deprecated version of Ads API

### ISSUE THREAD

**Issue by uargh** [lucascosta/facebook-js-ads-sdk#8]
I am getting the following error: "You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.".

Are you planning to update this sdk?

Full error message:
`400 GET https://graph.facebook.com/v2.7/act_********?fields=name&access_token=********
error { [FacebookRequestError: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.]
  name: 'FacebookRequestError',
  message: '(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.',
  stack: 'Error
    at FacebookRequestError.FacebookError [as constructor] (path/node_modules/facebook-ads-sdk/dist/cjs.js:196:16)
    at new FacebookRequestError (path/node_modules/facebook-ads-sdk/dist/cjs.js:221:93)
    at path/node_modules/facebook-ads-sdk/dist/cjs.js:321:15
    at tryCatcher (path/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (path/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (path/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (path/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (path/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (path/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (path/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (path/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)',
  status: 400,
  response:
   { error:
      { message: '(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.',
        type: 'OAuthException',
        code: 2635,
        fbtrace_id: '*******' } },
  method: 'GET',
  url: 'https://graph.facebook.com/v2.7/act_********?fields=name&access_token=*******' }`

**Comment by lucascosta** [comment]
Hi @uargh, as you can see on the changelog (https://developers.facebook.com/docs/marketing-api/changelog) the v2.7 is still available until April 2017. Also I could run the integration tests on 2.7. Please check.

**Comment by uargh** [comment]
Okay, I figured it out. The problem appears when you try to use the library with a newly created FacebookApp. Facebook sets the lowest compatible API-Version to the current one.

Using an older FacebookApp fixed the issue.

**Comment by lucascosta** [comment]
Cool @uargh

**Comment by MarkusPint** [comment]
Hey, if I only have newly created FB apps I can't use this SDK? I'm getting the same error.
